<div class="full-screen-slider">
    <div id="banner-slider-demo-4" class="owl-carousel owl-middle-narrow owl-banner-carousel">
        <div class="item" style="background:#f0f0f0;background-image:linear-gradient(#e8e8e8,#f0f0f0);position:relative;">
            <div style="width:100%;height:100%;background:url({{media url="wysiwyg/smartwave/porto/homepage/04/slider/slide1.jpg"}}) 80% center no-repeat; background-size:cover;"></div>
        <div class="slide1-content" style="width:100%;height:100%;position:absolute;left:0;top:0;">
            <div class="container" style="height:100%;position:relative;">
                <div class="content-area" style="position:absolute;top:37%;left:7%;text-align:center;">
                    <div style="margin:0;line-height:1;">
                        <img src="{{media url="wysiwyg/smartwave/porto/homepage/04/slider/quote.png"}}" alt="" class="quote" style="display:inline-block;vertical-align:middle;"/>
                        <em style="display:inline-block;vertical-align:middle;line-height:1;color:#fff;font-weight:300;font-style:normal;">DO YOU NEED A NEW</em>
                        <img src="{{media url="wysiwyg/smartwave/porto/homepage/04/slider/quote.png"}}" alt="" class="quote" style="display:inline-block;vertical-align:middle;"/>
                    </div>
                    <h2 style="font-weight:800;color:#fff;line-height:1;">eCOMMERCE?</h2>
                    <p style="font-weight:300;color:#fff;line-height:1;">Check our options and features.</p>
                </div>
            </div>
        </div>
    </div>
    <div class="item" style="background:#f0f0f0;background-image:linear-gradient(#e8e8e8,#f0f0f0);position:relative;">
        <div style="width:100%;height:100%;background:url({{media url="wysiwyg/smartwave/porto/homepage/04/slider/slide2.jpg"}}) 20% center no-repeat; background-size:cover;"></div>
    <div class="slide2-content" style="width:100%;height:100%;position:absolute;left:0;top:0;">
        <div class="container" style="height:100%;position:relative;">
            <div class="content-area" style="position:absolute;top:40%;right:20%;text-align:left;">
                <em style="display:block;line-height:1;color:#fff;font-weight:300;font-style:normal;">up to <b>70%</b> off!</em>
                <h2 style="font-weight:600;color:#fff;line-height:1;">HUGE <b style="font-weight:800;">SALE</b></h2>
                <p style="font-weight:600;color:#fff;line-height:1;">Fashion<span class="split">-</span>Electronics<span class="split">-</span>Gifts<span class="split">-</span>Music<span class="split">-</span>Sports</p>
                <div style="text-align:right;"><a href="#" class="btn btn-default" style="border:0;background-color:#fefefe;color:#777;font-weight:600;">SHOP NOW</a></div>
            </div>
        </div>
    </div>
</div>
<div class="item" style="background:#f0f0f0;background-image:linear-gradient(#e8e8e8,#f0f0f0);position:relative;">
    <div style="width:100%;height:100%;background:url({{media url="wysiwyg/smartwave/porto/homepage/04/slider/slide3.jpg"}}) center center no-repeat; background-size:cover;"></div>
<div class="slide3-content" style="width:100%;height:100%;position:absolute;left:0;top:0;">
    <div class="container" style="height:100%;position:relative;">
        <div class="content-area" style="position:absolute;left:0;top:40%;text-align:center;width:100%;">
            <div style="display:inline-block;">
                <em style="display:block;line-height:1;margin:0;color:#fff;font-weight:300;font-style:normal;text-align:right;">It’s time to feel</em>
                <h2 style="font-weight:600;color:#fff;line-height:1;text-align:center;">THE <b style="font-weight:800;">POWER</b></h2>
                <div style="text-align:right;"><a href="#" class="btn btn-default" style="border:0;background-color:#fefefe;color:#777;font-weight:600;">SHOP NOW</a></div>
            </div>
        </div>
    </div>
</div>
</div>
</div>
<script type="text/javascript">
    require([
        'jquery',
        'owl.carousel/owl.carousel.min'
    ], function ($) {
        $("#banner-slider-demo-4").owlCarousel({
            items: 1,
            autoplay: true,
            autoplayTimeout: 5000,
            autoplayHoverPause: true,
            navRewind: true,
            dots: false,
            animateIn: 'fadeIn',
            animateOut: 'fadeOut',
            loop: true,
            nav: true,
            navText: ["<em class='porto-icon-chevron-left'></em>","<em class='porto-icon-chevron-right'></em>"]
        });
        $(".main-container").remove();
    });
</script>
</div>
<div class="row" style="margin:0;">
    <div class="col-md-6 col-md-offset-3" style="padding:0;">
        <div class="brand-container">
            <div class="top-content">
                <img src="{{media url="wysiwyg/planet/porto_child/homepage/brazilian_soccer_brand.png"}}" alt="" />
            </div>
            <div class="bottom-content">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut at est arcu. Proin sit amet dui id ex viverra dapibus. Sed suscipit erat id enim efficitur, eget suscipit tortor aliquam.</p>
            </div>
        </div>
    </div>
</div>
<div class="row row-margin" style="margin:0;background-color:#f9f9f9;">
    <div class="col-sm-6 sm-f-right" style="padding:0;">
        <div id="half-image-1" style="background:url({{media url="wysiwyg/planet/porto_child/homepage/PLANETA_FUTEBOL-2.jpg"}}) center left no-repeat;background-size:cover;width:100%;">
            <img src="{{media url="wysiwyg/planet/porto_child/homepage/PLANETA_FUTEBOL-2.jpg"}}" alt="" style="    max-height: 549px;
            opacity: 0;"/>
        </div>
    </div>
    <div class="col-sm-6 sm-f-right" style="padding:0;">
        <div class="brand-container center">
            <div class="top-content">
                <p class="brand-title">
                    Camisetas Estampadas
                </p>
            </div>
            <div class="bottom-content">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut at est arcu. Proin sit amet dui id ex viverra dapibus. Sed suscipit erat id enim efficitur, eget suscipit tortor aliquam.</p>
            </div>
        </div>
        <div id="half-image-1" style="background:url({{media url='wysiwyg/planet/porto_child/homepage/II9A0569.jpg'}}) center left no-repeat;background-size:cover;width:100%;">
            <img src="{{media url="wysiwyg/planet/porto_child/homepage/II9A0569.jpg"}}" alt="" style="    max-height: 549px;
            opacity: 0;"/>
        </div>
    </div>
</div>
<div class="row row-margin" style="margin:0;background-color:#f9f9f9;">
    <div class="col-sm-12" style="padding:0;">
        <div class="brand-container center dark">
            <div class="top-content">
                <p class="brand-title">
                    Bermudas Sarja
                </p>
            </div>
            <div class="bottom-content">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut at est arcu. Proin sit amet dui id ex viverra dapibus. Sed suscipit erat id enim efficitur, eget suscipit tortor aliquam.</p>
            </div>
        </div>
        <div id="half-image-1" style="background:url({{media url='wysiwyg/planet/porto_child/homepage/IMG_1535_2.jpg'}}) center left no-repeat;background-size:cover;width:100%;">
            <img src="{{media url="wysiwyg/planet/porto_child/homepage/IMG_1535_2.jpg"}}" alt="" style="    max-height: 549px;
            opacity: 0;"/>
        </div>
    </div>
</div>
<div class="row row-margin" style="margin:0;background-color:#f9f9f9;">
    <div class="col-sm-6 sm-f-right" style="padding:0;">
        <div class="brand-container center">
            <div class="top-content">
                <p class="brand-title">
                    Camisas Polo
                </p>
            </div>
            <div class="bottom-content">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut at est arcu. Proin sit amet dui id ex viverra dapibus. Sed suscipit erat id enim efficitur, eget suscipit tortor aliquam.</p>
            </div>
        </div>
        <div id="half-image-1" style="background:url({{media url='wysiwyg/planet/porto_child/homepage/Foto_blur.jpg'}}) center left no-repeat;background-size:cover;width:100%;">
            <img src="{{media url="wysiwyg/planet/porto_child/homepage/Foto_blur.jpg"}}" alt="" style="    max-height: 549px;
            opacity: 0;"/>
        </div>
    </div>
    <div class="col-sm-6 sm-f-right" style="padding:0;">
        <div id="half-image-1" style="background:url({{media url="wysiwyg/planet/porto_child/homepage/Foto.jpg"}}) center left no-repeat;background-size:cover;width:100%;">
            <img src="{{media url="wysiwyg/planet/porto_child/homepage/Foto.jpg"}}" alt="" style="    max-height: 549px;
            opacity: 0;"/>
        </div>
    </div>
</div>
<div class="row row-margin" style="margin:0;background-color:#f9f9f9;">
    <div class="col-sm-6 sm-f-right" style="padding:0;">
        <div id="half-image-1" style="background:url({{media url='wysiwyg/planet/porto_child/homepage/Foto2.jpg'}}) center left no-repeat;background-size:cover;width:100%;">
            <img src="{{media url="wysiwyg/planet/porto_child/homepage/II9A0569.jpg"}}" alt="" style="    max-height: 549px;
            opacity: 0;"/>
        </div>
    </div>
    <div class="col-sm-6 sm-f-right" style="padding:0;">
        <div class="brand-container center">
            <div class="top-content">
                <p class="brand-title">
                    Camisas Sociais
                </p>
            </div>
            <div class="bottom-content">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut at est arcu. Proin sit amet dui id ex viverra dapibus. Sed suscipit erat id enim efficitur, eget suscipit tortor aliquam.</p>
            </div>
        </div>
        <div id="half-image-1" style="background:url({{media url="wysiwyg/planet/porto_child/homepage/Foto2_blur.jpg"}}) center left no-repeat;background-size:cover;width:100%;">
            <img src="{{media url="wysiwyg/planet/porto_child/homepage/PLANETA_FUTEBOL-2.jpg"}}" alt="" style="    max-height: 549px;
            opacity: 0;"/>
        </div>
    </div>
</div>
<script type="text/javascript">
    require([
        'jquery'
    ], function ($) {
        $("#half-image-1").css("min-height",$("#half-content-1").outerHeight()+"px");
        $("#half-image-2").css("min-height",$("#half-content-2").outerHeight()+"px");
        setTimeout(function(){
            $("#half-image-1").css("min-height",$("#half-content-1").outerHeight()+"px");
            $("#half-image-2").css("min-height",$("#half-content-2").outerHeight()+"px");
        }, 5000);
        $(window).resize(function(){
            setTimeout(function(){
                $("#half-image-1").css("min-height",$("#half-content-1").outerHeight()+"px");
                $("#half-image-2").css("min-height",$("#half-content-2").outerHeight()+"px");
            }, 500);
        });
    });
</script>
