<div class="admin__fieldset-wrapper-content">
    <fieldset class="admin__fieldset">
        <form action="<?= $this->getUrl("product_import/*/process");?>"
              class="admin__fieldset form-submit"
              enctype="multipart/form-data"
              method="post"
        >
            <div class="page-main-actions">
                <div class="page-actions-placeholder" style=""></div>
                <div class="page-actions" data-ui-id="page-actions-toolbar-content-header">
                    <div class="page-actions-inner">
                        <div class="page-actions-buttons">
                            <button id="import_file"
                                    title="Save and Continue Edit"
                                    type="button"
                                    class="action-
                                    scalable save ui-button
                                    ui-widget ui-state-default
                                    ui-corner-all ui-button-text-only ui-button-text"
                            >
                                <span class="admin__field">
                                    <span class="admin__field-label xlsx_file">
                                        <label for="xlsx_file" class="file-input">
                                            <span>Import excel file</span>
                                        </label>
                                    </span>
                                    <span class="admin__field-control hidden">
                                        <input
                                            id="xlsx_file"
                                            type="file"
                                            class="admin__control-file"
                                            name="xlsx_file"
                                        />
                                    </span>
                                </span>
                            </button>

                            <?= $this->getNewOrderHtml(); ?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="admin__field hidden">
                <button
                    type="submit"
                    class="action-secondary submit-import-product"
                    data-index="create_configurable_products_button">
                    <span>Import</span>
                </button>
            </div>
            <input type="hidden" name="form_key" value="<?= $this->getFormKey(); ?>"/>
        </form>
    </fieldset>
    <fieldset class="admin__fieldset">
        <?= $this->getGridHtml(); ?>
    </fieldset>
</div>
