<div class="admin__scope-old">
    <div class="fieldset-wrapper customer-information">
        <div class="fieldset-wrapper-title">
            <span class="title">Personal Information</span>
        </div>
        <table class="admin__table-secondary">
            <tbody>
            <tr>
                <td>Full Name: <?= $this->getName(); ?></td>
                <td>Tax/VAT Number: <?= $this->getTaxVat(); ?></td>
                <td>Email: <?= $this->getEmail(); ?></td>
            </tr>
            <tr>
                <td>Account Lock: <?= $this->getStatus(); ?></td>
                <td>Group Customer: traditional trade</td>
                <td>% Discount: 5</td>
            </tr>
            <tr>
                <td colspan="3">
                    <address>
                        <strong>Default Billing Address</strong>
                       Rua joao simoes de souza; 430; ap 153 bloco A; Parque rebouças; São Paulo ,  Sao Paulo, 05734140; Brazil; T: 11 5195-1335
                    </address>
                </td>
            </tr>
            </tbody>
        </table>
    </div>
</div>