<div class="admin__fieldset-wrapper-content">
    <fieldset class="admin__fieldset">
        <form action="<?php echo $this->getUrl("agent/*/process") ?>"
              class="admin__fieldset form-submit"
              enctype="multipart/form-data"
              method="post"
        >
            <div class="admin__field">
                <div class="admin__field-label xlsx_file">
                    <label for="xlsx_file" class="action-default primary">
                        <span>Import excel file</span>
                    </label>
                </div>
                <div class="admin__field-control hidden">
                    <input
                        id="xlsx_file"
                        type="file"
                        class="admin__control-file"
                        name="xlsx_file"
                    />
                </div>
            </div>
            <div class="admin__field hidden">
                <button type="submit" class="action-secondary submit-import" data-index="create_configurable_products_button">
                    <span>Import</span>
                </button>
            </div>
            <input type="hidden" name="form_key" value="<?php echo $this->getFormKey(); ?>" />
        </form>
    </fieldset>

    <fieldset class="admin__fieldset">
        <?php echo $this->getGridHtml() ?>
    </fieldset>
</div>
